### ISSUE TITLE
Build PySide2 5.9 branch

### ISSUE THREAD

**Issue by fredrikaverpil** [fredrikaverpil/pyside2-wheels#63]
Let's try this 💪

**Comment by leycec** [comment]
Thanks for tracking this, Fred. Once you and your muscle-bound fingers succeed at supporting the `5.9` branch, we'll follow suite on Gentoo. If you run into any non-trivial hiccups along the way, <sup>_...like, say, it burned down your house_</sup> it would be quite helpful if you could explicitly note that and any solutions you also uncovered here.

Relatedly, **The Qt Company should hire you.** No, *really.* You're clearly investing more effort into publishing PySide2 wheels than they are – and that's something they should have prioritized two years ago. Until then, here is to your mighty thews! :weight_lifting_man:

**Comment by fredrikaverpil** [comment]
> You're clearly investing more effort into publishing PySide2 wheels than they are

I'm not sure that's true, but it's not on at the top of their priorities yet. I hope this'll change if they see a high demand for it though. From what I understand, `setup.py` needs an overhaul as of now.

**Comment by fredrikaverpil** [comment]
I consider this blocking me starting working on 5.9: https://bugreports.qt.io/projects/PYSIDE/issues/PYSIDE-557

**Comment by leycec** [comment]
I agree it's *garbage-tier* coding practice that the `PySide2.__version__` field hasn't changed since [Tony Iommi](https://rateyourmusic.com/artist/black-sabbath-1) first gave THC a meaning, but is [PYSIDE-557](https://bugreports.qt.io/projects/PYSIDE/issues/PYSIDE-557) really a hard blocker for `5.9` work?

Not that I'm complaining. <sup>_i'm totally complaining_</sup>

I wouldn't particularly want to work on `5.9`, either. And I'm not. But how does the QtC's failure to explicitly version impact wheel development? Maybe it does? I know so little yet say so much.

**Comment by fredrikaverpil** [comment]
> but is PYSIDE-557 really a hard blocker for 5.9 work?

It's got more to do with how I should differentiate wheels naming than anything else. I was hoping to automate the naming process somehow. Please see, and weigh in, over at https://github.com/fredrikaverpil/pyside2-wheels/issues/87

Since [PYSIDE-557](https://bugreports.qt.io/projects/PYSIDE/issues/PYSIDE-557) got implemented yesterday (and in the wheels built yesterday) there's nothing blocking anymore, except the time I have to devote to this project...

**Comment by leycec** [comment]
> Since PYSIDE-557 got implemented yesterday (and in the wheels built yesterday)

*Ah-ha....* Missed that stealth Gerrit commit.

> except the time I have to devote to this project...

Someone should remunerate you for this. That someone is not me, but they exist and they are probably QtC. Capitalism doth love its unpaid volunteers a bit *too* much, methinks. <sup>_shoutout to [/r/BasicIncome](http://reddit.com/r/BasicIncome)_<sup>

**Comment by carmelov** [comment]
We will be devoted to you, if you can find the time to implement Qt 5.9

**Comment by fredrikaverpil** [comment]
Because of the recent [release of PySide2 on Anaconda Cloud](https://github.com/fredrikaverpil/pyside2-wheels/issues/95), I believe we should join forces with them ([qt-feedstock](https://github.com/conda-forge/qt-feedstock), [pyside2-feedstock](https://github.com/conda-forge/pyside2-feedstock)) and provide a 5.9 build of Qt and PySide2 there instead of here. But that's just me.

**Comment by fredrikaverpil** [comment]
Please see the new repositories for standalone wheels:

- [https://github.com/fredrikaverpil/pyside2-windows](pyside2-windows)
- [https://github.com/fredrikaverpil/pyside2-macos](pyside2-macos)
- [https://github.com/fredrikaverpil/pyside2-linux](pyside2-linux)
