### ISSUE TITLE
python 3.6 support

### ISSUE THREAD

**Issue by bjquinn** [fredrikaverpil/pyside2-wheels#77]
Would it be reasonable to ask for python 3.6 wheels?

**Comment by fredrikaverpil** [comment]
Sure. I have very limited time on my hands though, so you're free to do a PR or suggest how to do this on the platform(s) you're primarily interested in.

**Comment by bjquinn** [comment]
Yep, don't we all.  :)

There is a possibility that I'll pursue this further myself, and if I do, I'll make sure to share here.  I've put a little bit of effort into this but haven't gotten anywhere yet.

**Comment by fredrikaverpil** [comment]
Thanks @bjquinn - I'll leave this issue open as a reminder to get this done.

**Comment by fredrikaverpil** [comment]
I just added a few Dockerfiles for Python 3.6 which should generate wheels in Bintray shortly.

However, I had [issues building PySide2 with Python 3.6 on Ubuntu](https://travis-ci.org/fredrikaverpil/pyside2-wheels/builds/266674026?utm_source=github_status&utm_medium=notification). Not sure why. I'm tracking this in a [separate branch](https://github.com/fredrikaverpil/pyside2-wheels/tree/feature/ubuntu-python3.6). Any help here is appreciated.

**Comment by bjquinn** [comment]
Awesome!  Sadly, it appears I'm not cool enough, and I get a "Forbidden!" when clicking on any of the wheel file downloads.

**Comment by fredrikaverpil** [comment]
Hm... yes, it seems like the new wheels build/upload resulted in some kind of rate limit on Bintray. I've emailed them about it.

EDIT: Wheels can now be downloaded. For more info on that, refer to this issue: https://github.com/fredrikaverpil/pyside2-wheels/issues/84

**Comment by fredrikaverpil** [comment]
I'll set up a separate issue for the Ubuntu Trusty Python 3.6 wheels.

**Comment by bjquinn** [comment]
Thanks!  Using the Windows version, works great.
