### ISSUE TITLE
A formal request to have QtC provide a PySide2 wheel

### ISSUE THREAD

**Issue by fredrikaverpil** [fredrikaverpil/pyside2-wheels#78]
If you feel like I do, and wish to see an official, standalone and portable PySide2 wheel coming from The Qt Company (QtC) themselves, please go ahead and cast a vote (upper right hand side) on this formal request to do so in their bug tracker:
https://bugreports.qt.io/browse/PYSIDE-558

It may require you to create an account, and I would like to ask you to take a minute or two and not skip this. It would be valuable to show QtC how many are actually looking forward to this in order for them to prioritize the development which needs to be planned and financed.

Thanks.

**Comment by leycec** [comment]
I have [dutifully played my part.](https://bugreports.qt.io/browse/PYSIDE-558?focusedCommentId=367294&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-367294) :loud_sound: :loud_sound: :loud_sound:

**Comment by bjquinn** [comment]
Me too, just voted.
