### ISSUE TITLE
Wheels can't be downloaded

### ISSUE THREAD

**Issue by ccordoba12** [fredrikaverpil/pyside2-wheels#84]
Hi @fredrikaverpil, I'm using your wheels to test a project with PySide2, but it seems you updated them today (or in the last few days) and now they can't be downloaded.

For example, try this link:

https://dl.bintray.com/fredrikaverpil/pyside2-wheels/ubuntu14.04/PySide2-5.6-cp27-none-linux_x86_64.whl

and it will redirect you to a forbidden page.

**Comment by fredrikaverpil** [comment]
Yes, for some reason, a rate limit went into effect over at Bintray. Not sure what could've triggered that. I've emailed them.

**Comment by ccordoba12** [comment]
Thanks!

**Comment by fredrikaverpil** [comment]
In the meanwhile, you can build the wheel locally using the `docker build` and `docker run` commands outlined in each platform's markdown file.

**Comment by bjquinn** [comment]
This seems to be resolved now.  I can download files again.  Would recommend closing this issue unless others are still having problems.

**Comment by ccordoba12** [comment]
@fredrikaverpil, what was the problem?

**Comment by fredrikaverpil** [comment]
I'm still waiting for feedback on exactly what triggered this, but it seems like I reached the 10GB storage limit. Closing this for now. I'll report back with more info as I know more.
