### ISSUE TITLE
Standalone wheel

### ISSUE THREAD

**Issue by bjquinn** [fredrikaverpil/pyside2-wheels#92]
Interested in seeing if there's an chance of getting standalone versions of the wheels.  @leycec mentioned a --standalone option for setup.py in #44, don't know if that might be useful.

**Comment by fredrikaverpil** [comment]
I forgot to write in that thread that `--standalone` is a dead end, unfortunately. It doesn't work. I've tried it. Like many other things in `setup.py`, it's been left there since the PySide(1) days. You can see for yourself what it does here: http://code.qt.io/cgit/pyside/pyside-setup.git/tree/setup.py?h=5.6#n1018

I'm guessing that the files which should be copied there are in fact not properly copied, perhaps similarly as in #44.

This (standalone wheels) is what everyone wants and it would be pure gold to have. Unfortunately, I don't have the time available for such a task.

**Comment by fredrikaverpil** [comment]
By the way, if you're on Windows you can check this out: https://github.com/fredrikaverpil/pyside2-wheels/issues/69

**Comment by bjquinn** [comment]
Thanks! That accomplished what I was trying to do on Windows.

**Comment by bjquinn** [comment]
How is that different from standalone?

**Comment by fredrikaverpil** [comment]
What do you mean?
Would you consider the Windows wheel standalone?

To me, it doesn't seem properly configured to be standalone even if it bundles a lot of the right stuff. I'm not sure it has everything bundled although it clearly has a lot more than the Linux/macOS wheels.

**Comment by bjquinn** [comment]
I don't know what might still be missing, but for me, setting the QT_QPA_PLATFORM_PLUGIN_PATH to the platforms folder under site-packages seems to work as well as setting it to C:\Qt\Qt5.6.2\5.6\msvc2015_64\plugins\platforms.  And not setting it at all results in the error you referenced in #69, so it doesn't appear to be getting Qt libraries from anywhere else, and I don't have anything in any other environment variables pointing to anything for Qt.  I don't know if there are features I'm not using or something, but I haven't run into anything yet.

**Comment by fredrikaverpil** [comment]
It's possible that everything is properly bundled with the Windows wheel and that some configuration is missing to tell PySide2 where to find the DLL files. I found out about the `QT_QPA_PLATFORM_PLUGIN_PATH` and to me it seems like that was a workaround to achieve portability on Windows – but I only tested this with a couple of simple commands and would assume the wheel is not properly installed for portability without it (the environment variable). I have no idea what other things may be misconfigured (or not).

However, on Unix, wheels doesn't have any of the required Qt libraries bundled.

**Comment by fredrikaverpil** [comment]
Please see then new repositories for standalone wheels:

- [https://github.com/fredrikaverpil/pyside2-windows](pyside2-windows)
- [https://github.com/fredrikaverpil/pyside2-macos](pyside2-macos)
- [https://github.com/fredrikaverpil/pyside2-linux](pyside2-linux)
