### ISSUE TITLE
PySide2 now available in Anaconda Cloud; supersedes this project

### ISSUE THREAD

**Issue by fredrikaverpil** [fredrikaverpil/pyside2-wheels#95]
### PySide2 in Anaconda Cloud

You can now install PySide2 using conda:

```
conda config --add channels conda-forge
conda install pyside2
```

The feedstock (source, docs) lives here: https://github.com/conda-forge/pyside2-feedstock

I encourage everyone using the wheels generated from this project to stop doing that and instead start using conda, as this is a much more reliable build of PySide2 (built from source from the ground up), backed up by the fantastic [conda-forge](https://conda-forge.org) build system.

PySide2 is built here: https://github.com/conda-forge/pyside2-feedstock
PySide2 source: http://code.qt.io/cgit/pyside/pyside-setup.git/
Qt is built here: https://github.com/conda-forge/qt-feedstock

I believe we should focus and join forces to move from this project over to those projects.

### pyside2-wheels project superseded

I consider this (pyside2-wheels) project superseded by the pyside2-feedstock altough my project originally had a different goal; to provide portable PySide2 wheels on multiple platforms. The reason for drawing this drastic conclusion is:

- PySide2 with conda is built from Qt 5.6 source
- PySide2 with conda is more complete (modules-wise) than this project's wheels
- PySide2 with conda is built using the rigorous conda-forge build system
- conda-forge has a massive following

I'm sorry to say I will probably not develop this project much further without input from the community, although any PRs are still very much welcome, as I still think that work can be done here to generate portable wheels using pre-existing `apt-get`, `yum` and `brew` builds of Qt. For anyone who is interested in proceeding with such R&D, [`setup.py`](http://code.qt.io/cgit/pyside/pyside-setup.git/tree/setup.py?h=5.6) should be the main focus of improvement. But then again, you should be contributing to the [`pyside-setup`](http://code.qt.io/cgit/pyside/pyside-setup.git/) project over at QtC, not this project.

**Comment by pe224** [comment]
Thanks for your effort on this.
I also think that for wider adoption it is important to get wheel support as fast as possible.

To me it seems that the Windows part of this is more or less solved.
I tried the binary from [this StackOverflow answer](https://stackoverflow.com/a/44672926/3764699) which worked perfectly standalone - and it's Qt 5.9.
Maybe you could ask the author (Claudius Hansch) for build recipes as it seems that the conda crew is not keen on updating their Qt version?

**Comment by albertosottile** [comment]
While I do agree that conda is much more versatile and reliable than custom wheels, I still have a concern: redistribute apps. Is it possible to pack a .app with binaries taken from conda and distribute it? In other words, what is the license of conda binaries? I could not find an answer to this anywhere.

**Comment by fredrikaverpil** [comment]
Please see the new repositories for standalone wheels:

- [https://github.com/fredrikaverpil/pyside2-windows](pyside2-windows)
- [https://github.com/fredrikaverpil/pyside2-macos](pyside2-macos)
- [https://github.com/fredrikaverpil/pyside2-linux](pyside2-linux)
